// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package foosball.com.dpwn.model;

import foosball.com.dpwn.model.Team;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Team_Roo_Configurable {
    
    declare @type: Team: @Configurable;
    
}
