// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package foosball.com.dpwn.model;

import foosball.com.dpwn.model.UserTeamPK;
import java.io.Serializable;

privileged aspect UserTeamPK_Roo_Serializable {
    
    declare parents: UserTeamPK implements Serializable;
    
    private static final long UserTeamPK.serialVersionUID = 1L;
    
}
